service: example-api

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin

provider:
  name: aws
  run-time: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  graphql:
    handler: graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
        
